# -*- coding: utf-8 -*-
"""peso_gabriel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOVLR-tjLd3k2JCFFJRgoFDn71_VcLMh
"""

from flask import Flask, request, jsonify
from flask_cors import CORS  # Importa o CORS
import joblib  # Importa o joblib
import numpy as np  # Necessário para manipular os arrays de índices

# Cria a instância do aplicativo Flask
app = Flask(__name__)

# Habilita CORS para todas as rotas, permitindo que o Front-End (Java/JS) acesse esta API
CORS(app)

# --- Carregamento do Modelo ---
try:

    data = joblib.load('modelo_utlc_apps_sentimento.pkl')  # Carrega o arquivo .pkl
    model = data['model']  # Obtém o modelo
    vectorizer = data['vectorizer']  # Obtém o vetor de características
    print("Modelo carregado com sucesso!")
except Exception as e:
    print(f"Erro: Erro ao carregar o modelo: {e}")
    model = None
    vectorizer = None

# Dicionário para mapear as classes de sentimento
LABEL_MAP = {
    "negative": "Negativo",
    "neutral": "Neutro",
    "positive": "Positivo"
}

# Define a rota para a previsão de sentimentos
@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Verifica se o modelo foi carregado antes de tentar usar
        if model is None or vectorizer is None:
            return jsonify({"erro": "Modelo de IA não está disponível."}), 503

        # Obtém os dados enviados na requisição
        dados = request.get_json()
        texto = dados.get('text') if dados else None

        # Verifica se o texto foi fornecido corretamente
        if not texto or len(texto.strip()) < 5:
            return jsonify({"erro": "Texto não fornecido ou muito curto."}), 400

        # Transforma o texto em um vetor de características
        X = vectorizer.transform([texto])

        # Realiza a previsão
        prediction_label = model.predict(X)[0]
        proba = float(model.predict_proba(X).max())  # Obtem a maior probabilidade

        return jsonify({
            "previsao": LABEL_MAP.get(prediction_label, "Desconhecido"),
            "probabilidade": round(proba, 2)
        })

    except Exception as e:
        # Caso ocorra algum erro, retorna a mensagem de erro
        import traceback
        traceback.print_exc()
        return jsonify({"erro": str(e)}), 500

if __name__ == '__main__':
    # Executa o aplicativo na porta 5000 e em todos os endereços disponíveis
    app.run(host="0.0.0.0", port=5000)
