version: '3.8'

services:

  # Serviço Python (microserviço de IA)
  sentimento-ia-python:
    container_name: sentimento-ia-python
    # Tag específica para o seu repositório único
    image: marcosynky/hackaones:python-ia
    build:
      context: ../Hackathon-One-Data-Science/Arquvios Data
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - sentiment-net

  # Serviço Java (API principal com Spring Boot)
  sentimento-api-java:
    container_name: sentimento-api-java
    # Tag específica para o seu repositório único
    image: marcosynky/hackaones:java-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sentimento-ia-python:
        condition: service_started
      db:
        condition: service_healthy
    ports:

      - "8081:8081"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_PROFILES_ACTIVE=prod
      - SENTIMENT_PYTHON_URL=http://sentimento-ia-python:5000/predict
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER_HACKATHON}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD_HACKATHON}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
    restart: unless-stopped
    networks:
      - sentiment-net

  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: postgres-sentiment
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=sentiment
      - POSTGRES_USER=${DB_USER_HACKATHON}
      - POSTGRES_PASSWORD=${DB_PASSWORD_HACKATHON}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_HACKATHON} -d sentiment"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentiment-net

volumes:
  postgres_data:

networks:
  sentiment-net:
    driver: bridge
