version: '3.8'

services:

  # Serviço Python (microserviço de IA)
  sentimento-ia-python:
    container_name: sentimento-ia-python
    build:
      context: ../Hackathon-One-Data-Science/Arquvios Data
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - sentiment-net

  # Serviço Java (API principal com Spring Boot)
  sentimento-api-java:
    container_name: sentimento-api-java
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sentimento-ia-python:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SENTIMENT_PYTHON_URL: http://sentimento-ia-python:5000/predict
      SPRING_DATASOURCE_URL: ${DB_URL}  # Usando a variável do .env
      SPRING_DATASOURCE_USERNAME: ${DB_USER_HACKATHON}  # Usando a variável do .env
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD_HACKATHON}  # Usando a variável do .env
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"
    restart: unless-stopped
    networks:
      - sentiment-net

  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: postgres-sentiment
    restart: unless-stopped
    environment:
      POSTGRES_DB: sentiment
      POSTGRES_USER: ${DB_USER_HACKATHON}  # Usando a variável do .env
      POSTGRES_PASSWORD: ${DB_PASSWORD_HACKATHON}  # Usando a variável do .env
      SPRING_DATASOURCE_URL: ${DB_URL}  # Usando a variável do .env

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sentiment"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentiment-net

volumes:
  postgres_data:

networks:
  sentiment-net:
    driver: bridge

